# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-07 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='summary',
            field=models.TextField(default=b'this beech'),
        ),
    ]
